# Generated by Django 4.0.4 on 2022-05-23 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Aberta', 'Aberta'), ('Fechada', 'Fechada'), ('Paga', 'Paga')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(max_length=56)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(max_length=256)),
                ('preco', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ComandaItens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('comanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bar.comanda')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bar.item')),
            ],
        ),
        migrations.AddField(
            model_name='comanda',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bar.funcionario'),
        ),
        migrations.AddField(
            model_name='comanda',
            name='itens',
            field=models.ManyToManyField(through='bar.ComandaItens', to='bar.item', verbose_name='Itens na comanda'),
        ),
        migrations.AddField(
            model_name='comanda',
            name='mesa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bar.mesa'),
        ),
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comandas', models.ManyToManyField(to='bar.comanda', verbose_name='Comandas')),
            ],
        ),
    ]
