# Generated by Django 4.0.4 on 2022-05-31 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comandaitens',
            options={'verbose_name_plural': 'Comanda Itens'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name_plural': 'Itens'},
        ),
    ]
