# Generated by Django 4.0.4 on 2022-05-31 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0002_alter_comandaitens_options_alter_item_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comanda',
            name='status',
            field=models.CharField(blank=True, choices=[('Aberta', 'Aberta'), ('Fechada', 'Fechada'), ('Paga', 'Paga')], max_length=20, null=True),
        ),
    ]
